### ISSUE TITLE
Nothing happens when i run test

### ISSUE THREAD

**Issue by hazleego** [Michal2SAB/Bitcoin-Stealer#1]
Nothing happens when i run test 

![image](https://user-images.githubusercontent.com/12928429/121779125-ba0b4600-cbcc-11eb-83f2-b1a80f758e8c.png)

**Comment by Michal2SAB** [comment]
If you run it from cmd, you should type test.bat since there's no run.bat in the test folder.

**Comment by hazleego** [comment]
ok thanks 
![image](https://user-images.githubusercontent.com/12928429/121779844-39e6df80-cbd0-11eb-8e2f-728fe0aa0d23.png)

**Comment by Michal2SAB** [comment]
Yup, there you go. That's what would happen if you found a matching bitcoin wallet & private key (seed). It also creates a success.txt file in the folder with more info.
