### ISSUE TITLE
just blank 

### ISSUE THREAD

**Issue by rashtug2** [Michal2SAB/Bitcoin-Stealer#15]
i have try it many times but it never run

**Comment by Michal2SAB** [comment]
More information pls.

**Comment by CryExo** [comment]
When you press run, the screen is just black. Nothing is running
![image](https://user-images.githubusercontent.com/12098579/145912195-6a5c8b20-6e51-4c1a-bf00-d894524d7736.png)

**Comment by CryExo** [comment]
Oh, it works, just there's no logging! If you need log delete comment in generate.js

**Comment by CryExo** [comment]
And what's the safe max amount of wallet addresses in riches.txt?

**Comment by petjal** [comment]
fwiw, I use a very slightly edited generator.js, and do this:

![image](https://user-images.githubusercontent.com/3526136/145923286-23b8ca88-e84b-4121-9ae0-a7b433a19db5.png)

I need to double check it with some test vectors...just in case.

**Comment by Michal2SAB** [comment]
> Oh, it works, just there's no logging! If you need log delete comment in generate.js

Yup, that's it.

There's no max amount for your riches.txt file but the smaller size the better for memory, performance and stuff like that.

**Comment by petjal** [comment]
(But in the end
It doesn't even matter 

https://youtu.be/8t5f7y7LT6k

)
