### ISSUE TITLE
Cannot find module "Coin key"

### ISSUE THREAD

**Issue by krycopter** [Michal2SAB/Bitcoin-Stealer#17]
What am i doing wrong? Thanks!

**Comment by petjal** [comment]
Do any of these help?

https://duckduckgo.com/?q=Cannot+find+module&ia=web

Perhaps?: 
`npm install coinkey`

README Requirements Step 2:
https://github.com/Michal2SAB/Bitcoin-Stealer/blob/c227bbc3f3e97b536c24823befddef1076583acf/README.md#requirements

```
~/dev/github.com/Michal2SAB/Bitcoin-Stealer/Linux$ npm install coinkey

up to date, audited 34 packages in 2s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
