### ISSUE TITLE
BTC

### ISSUE THREAD

**Issue by iqbiz** [Michal2SAB/Bitcoin-Stealer#20]
Hi Sir i need a guide how to run and where to download. I am new here thats why i am not able to find the app. I downloaded and install the Jason Key but after that what i have to do please guide.

**Comment by iqbiz** [comment]
Hi Sir i need a guidance that how to run and where to download. I am new here thats why i am not able to find the app. I downloaded and install the node.js but after that what i have to do please guide.

**Comment by iqbiz** [comment]
wow what a spirit and appreciation rather then making me learn something people are discouraging wow.

**Comment by sem1845** [comment]
Download the files from github. What happens when you run run.bat(windows) or run.sh(Linux)?

**Comment by iqbiz** [comment]
Sir totally lack on knowledge but if u give me help by video how to do then much helpful even i m ready to pay sir for this please have kinds hand
