### ISSUE TITLE
U r Only legit

### ISSUE THREAD

**Issue by iqbiz** [Michal2SAB/Bitcoin-Stealer#22]
Sir you are the only legit person on internet. So please guide how to install proper and run.
Sir need your help in that
If u make a upload a video on ur channel of all process from A to Z then it will be great help and even u can sell it
Please think on that need ur help

**Comment by Michal2SAB** [comment]
I got a strong feeling that you're trolling.. if so, what's the point?

**Comment by Nemo1202** [comment]
I am not sure if the other guy is trolling but I would appreciate your help as well

**Comment by CeemoneyX2** [comment]
Pls show me how to install the coin key package pls

**Comment by iqbiz** [comment]
Respect sir my God knows i am not trolling and why should i troll. Sir i really dont know this as i m total new thats why i asked you for the help as this developed by you. So kindly with very humble and very due respect help me in understanding how to install properly. Infact people in last issue i created trolled me alot and made fun of me but i want to learn thats why i m still here and keep on asking.

**Comment by iqbiz** [comment]
Sir seriously my God knows i dont know this all but wanted to learn so please dont take in in wrong way. Pleas help. Plus also help by telling any way or any wallet or any software develop by you in which we can cancel BTC unconfirmed TX without RBF protocol.

**Comment by CeemoneyX2** [comment]
Bro dm me on WhatsApp for tots ‪+1 (209) 992‑3579‬

**Comment by CeemoneyX2** [comment]
> Sir seriously my God knows i dont know this all but wanted to learn so please dont take in in wrong way. Pleas help. Plus also help by telling any way or any wallet or any software develop by you in which we can cancel BTC unconfirmed TX without RBF protocol.

Text me on WhatsApp

**Comment by iqbiz** [comment]
Dear [Michal2SAB](https://github.com/Michal2SAB) Sir you are replying and people on ur account trying to contact and somehow feel they are trying to scam. Sir please help

**Comment by CeemoneyX2** [comment]
How ??

**Comment by iqbiz** [comment]
> How ??

you want me to pay u $300 and without any test. this is not going to happen bro. sorry i simply said send me test and lets final deal.

**Comment by CeemoneyX2** [comment]
Send half I will drop the source code and zip file very simple once you see is real then you pay the balance that's only if you real or if you don't believe me this way then forget it
