### ISSUE TITLE
wont run

### ISSUE THREAD

**Issue by stafki** [Michal2SAB/Bitcoin-Stealer#25]
whenever i run it doesn't do anything

**Comment by DonnyDevIT** [comment]
I solved it, open file "generator.js"

where is 
    let privateKeyHex = r(64);
write then
    console.log(privateKeyHex);
    
    
so you will have
    function generate() {
    let privateKeyHex = r(64);
    console.log(privateKeyHex); //<-- added this

**Comment by SALTA77** [comment]
can u send all "generator.js" text it will be easier tm me pls

**Comment by DonnyDevIT** [comment]
"use strict";

process.title = "Bitcoin Stealer by Michal2SAB";

const CoinKey = require('coinkey');
const fs = require('fs');

const data = fs.readFileSync('./riches.txt');

function generate() {
    let privateKeyHex = r(64);
    
    let ck = new CoinKey(Buffer.from(privateKeyHex, 'hex'));
    
    ck.compressed = false;

    
    console.log(ck.publicAddress)
    if(data.includes(ck.publicAddress)){
        console.log("");
        process.stdout.write('\x07');
        console.log("\x1b[32m%s\x1b[0m", ">> Success: " + ck.publicAddress);
        var successString = "Wallet: " + ck.publicAddress + "\n\nSeed: " + ck.privateWif;
            
        
        fs.writeFileSync('./Success.txt', successString, (err) => {
            if (err) throw err; 
        })
        
        process.exit();
    }
}


function r(l) {
    let randomChars = 'ABCDF0123456789';
    let result = '';
    for ( var i = 0; i < l; i++ ) {
        result += randomChars.charAt(Math.floor(Math.random() * randomChars.length));
    }
    return result;
}

while(true){
    generate();
}

**Comment by Michal2SAB** [comment]
It is running and working, but logs are disabled for better speed.
