### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by barry-mcockiner** [Michal2SAB/Bitcoin-Stealer#26]
i installed coinkey and i have node,js and it throws this error
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'coinkey'
Require stack:
- C:\Projects\CoinForcer\generator.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (C:\Projects\CoinForcer\generator.js:5:17)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1103:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Projects\\CoinForcer\\generator.js'←[39m ]
}
Press any key to continue . . .

**Comment by Michal2SAB** [comment]
How did you install coinkey? I just wanna see if you did it right

**Comment by f1nnplays** [comment]
I have the same error

**Comment by timotie-tim** [comment]
u need to instal coinkey  by going into the console type cd coinkey and then npm i coinkey  though i dont know for sure if thats what i did but it comes close

**Comment by Michal2SAB** [comment]
You need to do 'npm i coinkey' inside the project folder, not outside of it. Or just do 'npm i -g coinkey'
