### ISSUE TITLE
Won't start, please help

### ISSUE THREAD

**Issue by timhly** [Michal2SAB/Bitcoin-Stealer#27]
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
←[90m    at new Hash (node:internal/crypto/hash:67:19)←[39m
←[90m    at Object.createHash (node:crypto:135:10)←[39m
    at CoinKey.get (C:\Users\sweat\node_modules\←[4meckey←[24m\lib\eckey.js:65:33)
    at CoinKey.get (C:\Users\sweat\node_modules\←[4mcoinkey←[24m\lib\coinkey.js:45:27)
    at generate (C:\Users\sweat\Desktop\Neuer Ordner (3)\generator.js:18:20)
    at Object.<anonymous> (C:\Users\sweat\Desktop\Neuer Ordner (3)\generator.js:45:5)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1097:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:975:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m {
  opensslErrorStack: [ ←[32m'error:03000086:digital envelope routines::initialization error'←[39m ],
  library: ←[32m'digital envelope routines'←[39m,
  reason: ←[32m'unsupported'←[39m,
  code: ←[32m'ERR_OSSL_EVP_UNSUPPORTED'←[39m
}

**Comment by claudiuko** [comment]
same

**Comment by Michal2SAB** [comment]
Check out some of these answers: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
