### ISSUE TITLE
Can it be made 31x faster?

### ISSUE THREAD

**Issue by Isitsmd** [Michal2SAB/Bitcoin-Stealer#3]
In your generator json, there is a line 14 about making the script 31x faster, will it work if I hide that line?

**Comment by Michal2SAB** [comment]
Yes. Either remove the entire line or put "//" before it. It will speed up the performance drastically and it won't log newly generated addresses in the console

**Comment by Isitsmd** [comment]
Ohh, Thanks. Can this code be used for finding an eth wallet?
