### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Matthias420666** [Michal2SAB/Bitcoin-Stealer#30]
i installed it via a zip and tried to run it but it does not work, can someone please help? thanks

**Comment by Matthias420666** [comment]
![image](https://user-images.githubusercontent.com/101425792/157936982-32880063-9d65-4330-83b4-e82d2e2fa546.png)
i get this image when i try to run it

**Comment by Michal2SAB** [comment]
You need to extract fiels from .zip, not try to run it from .zip
