### ISSUE TITLE
couldn't find module coinkey :(

### ISSUE THREAD

**Issue by Stnadageah** [Michal2SAB/Bitcoin-Stealer#31]
![image](https://user-images.githubusercontent.com/100540979/158731073-d8dadcd5-0f03-4cc4-8908-39ee3b6cb4f5.png)

i made "npm i coinkey"

![image](https://user-images.githubusercontent.com/100540979/158731078-ade3eafd-2f91-4ac5-8f9d-5761a9d4a9c8.png)

installed but couldnt find

**Comment by Michal2SAB** [comment]
Do this "npm i coinkey" inside the project folder, not outside of it. Or just do "npm i -g coinkey"
