### ISSUE TITLE
Problem with coinkey module

### ISSUE THREAD

**Issue by BlazeLPREAL** [Michal2SAB/Bitcoin-Stealer#32]
i´ve installed the coinkey module:

C:\Users\Finnr>npm i coinkey

up to date, audited 70 packages in 1s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

but it still says:

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'coinkey'
Require stack:
- D:\ETH\ETH mining\Windows\generator.js
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:102:18)[39m
    at Object.<anonymous> (D:\ETH\ETH mining\Windows\generator.js:5:17)
[90m    at Module._compile (node:internal/modules/cjs/loader:1103:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:981:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'D:\\ETH\\ETH mining\\Windows\\generator.js'[39m ]
}

**Comment by Michal2SAB** [comment]
Do this "npm i coinkey" inside the project folder, not outside of it. Or just do "npm i -g coinkey"
