### ISSUE TITLE
Doesnt seem to run

### ISSUE THREAD

**Issue by Ninjamoosefrog** [Michal2SAB/Bitcoin-Stealer#33]
so i followed you instructions and the video installed all dependencies on windows and ran the batch file.
All it is showing is the command box with flashing _ (underscore).
However in also used the ether-strealer too. did exactly the same process for that and works fine. command box with scrolling list of addresses.

Just cant seem to figure the bitcoin one out. 
Is there a minimum version of node.js to use?
think im using 13.x.x as im on win7.

Thanks
M

**Comment by Michal2SAB** [comment]
It's working, the logs are just disabled.
