### ISSUE TITLE
Some issue with file reader

### ISSUE THREAD

**Issue by telekall** [Michal2SAB/Bitcoin-Stealer#4]
Hi there!
How can I make sure that script is reading the address file on the main folder "riches.txt" 
I changed the file name and didn´t update the generator.js  and the script keeps running without any issue.
I guess it should stop  and throw some error messages.
But on the test folder, the script throw some error when i changed the test1.txt filename.
Can you check, thanks!

**Comment by Michal2SAB** [comment]
Riches.txt is supposed to be a file, not a folder. So if you made it a folder it won't work.

Can you show me the error?

**Comment by Isitsmd** [comment]
Nah, he is saying that even after renaming riches.txt file, the generator.js keeps on running. So, he is unsure whether the script checks through the riches.txt or not as it goes on without throwing an error

**Comment by Michal2SAB** [comment]
> Nah, he is saying that even after renaming riches.txt file, the generator.js keeps on running. So, he is unsure whether the script checks through the riches.txt or not as it goes on without throwing an error

It is. I think the reason it doesn't throw an error is because of the way it reads the file. The error is test.js must've been the "success" message that appears right before the program closes. Don't worry, it does go through the riches.txt file, I'm not sure why it doesn't throw an error tho
