### ISSUE TITLE
Error generator.js

### ISSUE THREAD

**Issue by linglonglong15** [Michal2SAB/Bitcoin-Stealer#40]
Error: Cannot find module 'C:\Windows\system32\generator.js'
←[90m    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:780:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

whats happening

**Comment by Michal2SAB** [comment]
Perhaps you did not unpack all files from the downloaded .zip

**Comment by neverm8** [comment]
Hey Michal,

I'm still a bit lost on this - have I got a 'hit' here or not?

Thx

[image: image.png]

**Comment by neverm8** [comment]
This might make it a bit clearer - I'm unsure what the green line at the
bottom is or why RED GREEN CHINESE is in 'Green' as I haven't had this
before - sorry mate, but a bit lost :(

**Comment by Michal2SAB** [comment]
> This might make it a bit clearer - I'm unsure what the green line at the bottom is or why RED GREEN CHINESE is in 'Green' as I haven't had this before - sorry mate, but a bit lost :(

I'm lost on what your issue is.

**Comment by neverm8** [comment]
Does this look like this program is running correctly?

Also am I running this on the right decoding setting - I'm just wondering
why the code has come up Japanese/Chinese - Can you let us know mate

Cheers
[image: image.png]

**Comment by neverm8** [comment]
Hey bro,

I've been working relentlessly on this and getting some joy at times but
then just get that 'fatal' in red and the thing stops running - it's doing
my head in as I didn't think it would be this hard lol

Anyway, check out in the snip shots what I'm talking about - I've
downloaded the stratosphere and still not on the moon! ha harr

Can you tamper with my settings so they are A1 and I can just get up and
running - it's the pain and torment of yeah/nah....

Appreciate any assistance as I should be concentrating more on real bill
paying work, but I'm a sucker for punishment arrrgghhh - I've got so much
running trying to find a winner I don't know if I'm Arthur or Martha!

Cheers bwuda!

[image: image.png]

[image: image.png]
