### ISSUE TITLE
>> Program Started and is working silently (edit code if you want logs)

### ISSUE THREAD

**Issue by rebull000** [Michal2SAB/Bitcoin-Stealer#42]
>> Program Started and is working silently (edit code if you want logs) but nothing happens the program is not working

**Comment by neverm8** [comment]
I’m hearing your pain - I can’t even get the run.bit to work

**Comment by rebull000** [comment]
I also couldn't run once. Make sure node and all such programs are on the same path. It helped me.

**Comment by neverm8** [comment]
This is far as I can get and not getting any closer to the problem despite me efforts 
- hopefully an easy fix but I ain't holdin me breath ----

**Comment by Michal2SAB** [comment]
This is not a problem. The program is working but silently (without anything showing on your console aka the logs)

**Comment by Lawanixxx** [comment]
i saw a success message with a new text file but is it encrypted? because its only numbers and few letters

**Comment by neverm8** [comment]
I keep getting **can't find specified pathway** - What should I be running on?

Attach to what kubes or cloud - but cloud is run locally?

And run through what kubes, docker, powershell or what?

Any help appreciated

I've got an Azure Cloud basic account and running Google cloud
