### ISSUE TITLE
 How do I notice a hit

### ISSUE THREAD

**Issue by Supercooltje** [Michal2SAB/Bitcoin-Stealer#43]
i was wondering if i can see if i get a hit

**Comment by Michal2SAB** [comment]
What is a hit?

**Comment by neverm8** [comment]
A happy ending :) - But yeah - what do we do once we possibly hit a vault cracker in terms of wallet distribution?

**Comment by Michal2SAB** [comment]
You use the found seed to transfer money over to your wallet.
