### ISSUE TITLE
do i have to put my wallet in riches.txt ?

### ISSUE THREAD

**Issue by ssjblue-xxx** [Michal2SAB/Bitcoin-Stealer#44]
my issue is in the title

**Comment by ssjblue-xxx** [comment]
if no, where do i put it?

**Comment by neverm8** [comment]
Yeah, whilst the program as you say may be running in the background - I
don’t know what it’s running as I never had a search box pop-up to even
enter a wallet ID that I wanted to search so I’m a little lost to tell you
the truth-

Any guidance would be appreciated.

Thx

**Comment by Michal2SAB** [comment]
> my issue is in the title

You put dormat bitcoin wallets in there. Wallets that are known to be rich and untouched for years.
