### ISSUE TITLE
How to check progress ?

### ISSUE THREAD

**Issue by rebull000** [Michal2SAB/Bitcoin-Stealer#45]
How do I check any progress? Number of converted keys?

**Comment by Michal2SAB** [comment]
If you enable logs and you add a simple counter to each log, you will see it. It's completely unnecessary though and it will slow down the program too much.

People.. I get it, logs and other stuff looks cool and all skids on yt do it.. but it's very unpractical with this program. We want this thing to go as fast as your machine allows for.
