### ISSUE TITLE
Where do i put my wallets for payouts

### ISSUE THREAD

**Issue by nekaius101** [Michal2SAB/Bitcoin-Stealer#46]
If i get a hit, where will it send the payout to?

**Comment by noahmajors** [comment]
edit the code and find the destination address. change it to your personal wallet

**Comment by neverm8** [comment]
What's this?

**Comment by Michal2SAB** [comment]
> If i get a hit, where will it send the payout to?

You're supposed to take the "hit" aka found "seed" and use it to transfer money manually to your wallet. But the chances of you finding a said hit are almost 0
