### ISSUE TITLE
No coinkey

### ISSUE THREAD

**Issue by adamoi** [Michal2SAB/Bitcoin-Stealer#47]
downloaded node.js and im not sure what to do with it?

**Comment by Michal2SAB** [comment]
Good first step, now please learn what node.js is and how to install programs.

**Comment by adamoi** [comment]
So @Michal2SAB what programs are to be installed?

**Comment by Michal2SAB** [comment]
Well, not any external programs. I meant how to run projects.

If you got NPM installed, you have to type `npm i` command inside the bitcoin stealer folder

**Comment by Garyrogers30214** [comment]
Mike.. how can I message you ? I have questions
