### ISSUE TITLE
riches.txt ( how many line btc address can put ? )

### ISSUE THREAD

**Issue by tareksibay** [Michal2SAB/Bitcoin-Stealer#5]
if i have a list with 2 million address it possible to check all ? with the generating 
i don't think so because no bloom file to loading the addresses, correct me if I'm wrong 

thanks

**Comment by Michal2SAB** [comment]
It's possible but the larger the file, the slower the process and higher potential for the memory leak error. The program is not checking the wallets you put in riches.txt, it's just generating a new wallet and it's seed and then looking in riches.txt if a matching wallet exists so it can then tell you that there was success and give you the seed for it.

**Comment by tareksibay** [comment]
Understand,

Thanks.
