### ISSUE TITLE
speed test

### ISSUE THREAD

**Issue by babadura** [Michal2SAB/Bitcoin-Stealer#55]
Hi bruh

show me pls how speedtest?

you write:

Results from a somewhat decent computer:

    1.56 million checks every 1 minute

I try to do logs with:
    fs.appendFileSync('./logs.txt', ck.publicAddress + '\n')

and its only ~6000 per second.

I understand that Filewtriting do programm slowly, but so much?

How can i check that its can be really ~1,56 checks every 1 min? Show me the way to check real speed

Thanks a lot

p.s. i have strong PC

**Comment by neverm8** [comment]
You'll bwuda - speed test ere

[image: image.png]

[image: image.png]

**Comment by neverm8** [comment]
These just seemed to get closed without answers or am I missing something?

**Comment by 0xinit** [comment]
@neverm8 yea kinda sus
