### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by Daplug01** [Michal2SAB/Bitcoin-Stealer#61]
Hello please can I have a video tut on how you install it?

**Comment by RoyNahar** [comment]
Don't bother bro. This stuff does work.. But it takes too long to crack. I have tried it. I ran it for 3 months. And nothing was found. Lol.

**Comment by Daplug01** [comment]
Thanks mate

**Comment by Daplug01** [comment]
Yo Roynahar message me please 
I have something to understand from you please

**Comment by RoyNahar** [comment]
> Yo Roynahar message me please 
> I have something to understand from you please 
> 

azroynahar@gmail.com mail me.. Or u can give me your telegram ID.

**Comment by Daplug01** [comment]
Copy !

**Comment by Daplug01** [comment]
> > Yo Roynahar message me please 
> > I have something to understand from you please 
> > 
> 
> azroynahar@gmail.com mail me.. Or u can give me your telegram ID. 

Yo check your email Brodie

**Comment by RoyNahar** [comment]
> > > Yo Roynahar message me please
> > > I have something to understand from you please
> > 
> > 
> > [azroynahar@gmail.com](mailto:azroynahar@gmail.com) mail me.. Or u can give me your telegram ID.
> 
> Yo check your email Brodie

nothing bro. u sure u email the right address?
