### ISSUE TITLE
Where to begin

### ISSUE THREAD

**Issue by idkwheretobegin** [Michal2SAB/Bitcoin-Stealer#63]
Hi there 👋🏻 I'm new and I don't know how and where to begin using stuff in github. Is there a video I could refer to to use this Bitcoin and Ethereum stealer? Hope to hear from you soon!

**Comment by bom3y** [comment]
download node.js, Github Desktop, and visual studio code. 
after ^ you can clone the code by opening the project via the green code drop down icon on this projects main page and opening with Git's desktop and then open in visual code.  

Or with cmd, after downloading the requirements;
>mkdir Bitcoin-Stealer
>cd Bitcoin-Stealer
>code .

you can manually copy the code from there

Although after that, I'm at a lost for how to include "coinkey" as a module,  I'm completely new to code as of today and could use a helping hand. Not sure if I'm suppose to copy code from https://github.com/cryptocoinjs/coinkey or how it fits in. I've been at this for only an hour so maybe time will tell.

**Comment by bom3y** [comment]
ok might've figured it out, in cmd I typed 

>npm i --save coinkey

and the .bat ran, i don't know if if there's anything to do from here

**Comment by idkwheretobegin** [comment]
> download node.js, Github Desktop, and visual studio code. 
> 
> after ^ you can clone the code by opening the project via the green code drop down icon on this projects main page and opening with Git's desktop and then open in visual code.  
> 
> 
> 
> Or with cmd, after downloading the requirements;
> 
> >mkdir Bitcoin-Stealer
> 
> >cd Bitcoin-Stealer/
> 
> >code .
> 
> 
> 
> you can manually copy the code from there
> 
> 
> 
> Although after that, I'm at a lost for how to include "coinkey" as a module,  I'm completely new to code as of today and could use a helping hand. Not sure if I'm suppose to copy code from https://github.com/cryptocoinjs/coinkey or how it fits in. I've been at this for only an hour so maybe time will tell.

Will these work for other projects as well? Could definitely use a youtube video guide for github 😆 Update me if you've figured it out too!(P.S. thank you for the reply 😄)

**Comment by Michal2SAB** [comment]
You can copy all projects on github like this. Or you can simply download the repository as a .zip or whatever you prefer, extract it and then follow the project's instructions on how to use/install/run whatever it is.
