### ISSUE TITLE
Is there a brake ? Stop command ? 

### ISSUE THREAD

**Issue by Levirusdzrzs** [Michal2SAB/Bitcoin-Stealer#67]
Hi, in the generator code, it will exit when success but there's no way to stop it manually.. Any suggestions ?

**Comment by Casyvina** [comment]
ctrl c to stop it

**Comment by Michal2SAB** [comment]
I mean, you can just exit the console.. it doesn't matter if you paused it or closed it.

**Comment by Levirusdzrzs** [comment]
Thanks, i got a good result 👍 after 7 days of continuous digging
