### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by nikolai777111** [Michal2SAB/Bitcoin-Stealer#78]
Hello. I have two questions : 
1 - Is the program searching for keys randomly or sequental from 0000000000000000000000000000000000000000000000000000000000000001 to ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
2 - Can i open more than 1 scripts at the same time so they can work separately?

**Comment by Michal2SAB** [comment]
Randomly, because in theory this makes a higher chance
Yes

**Comment by fengshui8** [comment]
Currently running 12 instances of the app, 
each instance is searching for a separate 1.9 million btc addresses (that begin with “1…”).  So actively searching across ~22.8 million btc addresses (that begin with “1…”).



This doesn’t affect my 64GB of good ram, but my CPU is throttling at 100%. Is this okay? Do you think it is underperforming significantly?  

Regardless, do you think it is still worth doing?

Won’t this up the likelihood of a hit significantly in the coming weeks/months? 

& What do you think the likelihood of a hit is?
