### ISSUE TITLE
Show Logs

### ISSUE THREAD

**Issue by RigidBoss** [Michal2SAB/Bitcoin-Stealer#79]
Hello man. I'm new about code, and i just run the script run.sh on termux. Can u help me about this? "Program Started and is working silently (edit code if you want logs)"
I want looking for logs if the program started. Thank for helping me.

**Comment by Michal2SAB** [comment]
In generator.js find these lines. And remove the // before console.log(ck.publicAddress). Then the line won't be grey and won't be a comment anymore. // before any line excludes the line from code and makes it a comment so it's not doing anything. Remove it to do something.

ck.compressed = false;
//console.log(ck.publicAddress)
