### ISSUE TITLE
Got Error

### ISSUE THREAD

**Issue by preritsidhu** [Michal2SAB/Bitcoin-Stealer#80]
![Capture](https://user-images.githubusercontent.com/130216533/233255903-9cff128e-cd32-4b6f-81e7-46433c29930e.PNG)
Cannot find module named 'coinkey'
![Capture](https://user-images.githubusercontent.com/130216533/233263234-a05147dd-d4d5-4cff-b015-e64fbf14a0ac.PNG)

**Comment by QVA0Rg** [comment]
You did not execute the "npm i" command

**Comment by preritsidhu** [comment]
sir can you please tell me where and how to do it please

**Comment by Michal2SAB** [comment]
Open cmd and type this command: "npm i coinkey -g"

**Comment by preritsidhu** [comment]
i did
![Capture](https://user-images.githubusercontent.com/130216533/233532129-afefe77d-0e2c-470f-9e1d-eb52e69f95b6.PNG)


but again it is showing error
![Capture2](https://user-images.githubusercontent.com/130216533/233532178-3e648eb8-e02b-4a80-bdbf-ea07b9cbfe83.PNG)

**Comment by preritsidhu** [comment]
> Open cmd and type this command: "npm i coinkey -g"



> Open cmd and type this command: "npm i coinkey -g"

i did 
![Capture 1](https://user-images.githubusercontent.com/130216533/233532545-1b2b82d6-372f-40b5-ba67-9b982fab64d1.PNG)
   


but again this happened

![Capture2](https://user-images.githubusercontent.com/130216533/233532663-3a05eab1-46c7-4070-b0a2-529528914a7c.PNG)
