### ISSUE TITLE
> Open cmd and type this command: "npm i coinkey -g"

### ISSUE THREAD

**Issue by preritsidhu** [Michal2SAB/Bitcoin-Stealer#81]
> Open cmd and type this command: "npm i coinkey -g"

> Open cmd and type this command: "npm i coinkey -g"

i did 
![Capture 1](https://user-images.githubusercontent.com/130216533/233532545-1b2b82d6-372f-40b5-ba67-9b982fab64d1.PNG)
   

but again this happened

![Capture2](https://user-images.githubusercontent.com/130216533/233532663-3a05eab1-46c7-4070-b0a2-529528914a7c.PNG)

_Originally posted by @preritsidhu in https://github.com/Michal2SAB/Bitcoin-Stealer/issues/80#issuecomment-1517201484_

**Comment by Michal2SAB** [comment]
Your node.js may not be installed properly

**Comment by rounakmaldi** [comment]
i too face the same problem and i reinstalled everything but the results are same as above.
please help

**Comment by harvs1444** [comment]
hi how do i edit the code to get the logs
