### ISSUE TITLE
what should i do next

### ISSUE THREAD

**Issue by preritsidhu** [Michal2SAB/Bitcoin-Stealer#82]
can anyone please help me with this 
what i supposed to do next
![btc michal](https://user-images.githubusercontent.com/130216533/233817773-57416833-3465-4f45-8bcd-6d6deef410cc.PNG)

**Comment by marssystems** [comment]
You don't need to do anything. When the program finds a match, it will display the results in the CMD window.

**Comment by preritsidhu** [comment]
> You don't need to do anything. When the program finds a match, it will display the results in the CMD window.

It is running since 3 days non stop , is this real or actually works?

**Comment by marssystems** [comment]
Yes - it is working.

To see how it works run the test.bat file in the Windows/test folder.

**Comment by preritsidhu** [comment]
> Yes - it is working.
> 
> To see how it works run the test.bat file in the Windows/test folder.

Thanks for your reply and for encouraging me.
It means a lot :)
