### ISSUE TITLE
Help me(

### ISSUE THREAD

**Issue by pizkogriz20smchlenochbolshoi** [Michal2SAB/Bitcoin-Stealer#83]
Hello, please tell me how to remove this error, thanks in advance.
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/113055608/9dda7d83-cf12-4aa7-b227-5dfba7305ae8)

**Comment by Michal2SAB** [comment]
If you have edited the code in any way, I can't help you without you providing me the modified code

**Comment by OmVaswani** [comment]
Hello, help! 
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/62178966/ba9aa4f0-cfff-459d-9021-ecec1c6222ef)

**Comment by DennisMihaltan** [comment]
I have the same problem...

**Comment by x3roxismygood** [comment]
> 

use npm install coinkey

**Comment by Mink232** [comment]
> 

Where exactly did you put the npm files? i used CMD to install "npm i" and have the node setup but keep getting "Code: Module not found" when i run the .bat

**Comment by Mink232** [comment]
Do i have to donate to use the module?

**Comment by DennisMihaltan** [comment]
@xx3roxx 

It works... thank you

**Comment by harvs1444** [comment]
how can i see the logs can somebody tell me

**Comment by maxxxxing** [comment]
> @xx3roxx
> 
> It works... thank you

really??? how?? i wrote it and it downloaded but it still popped up the same thing
