### ISSUE TITLE
No Address

### ISSUE THREAD

**Issue by OverloadedTech** [Michal2SAB/Bitcoin-Stealer#84]
Hey,
Just wondering if there can be a way to leave this script there making its searches without putting necessarily some target addresses that vould surely limit and slow down the process
Thanks

**Comment by Michal2SAB** [comment]
Well yes, but it would be even slower. You would have to check every single new bitcoin wallet generated on blockchain or whatever which would require internet connection, making a request to the website etc. And if you want a result of just any random wallet which is worth $0 then every single wallet generated is a working one, it would be pointless.

**Comment by OverloadedTech** [comment]
Ok thanks anyway
