### ISSUE TITLE
No result!

### ISSUE THREAD

**Issue by nscpro** [Michal2SAB/Bitcoin-Stealer#85]
Hi. This file works my vps 24/7 and after one week no result. Why?

**Comment by Michal2SAB** [comment]
Because there are 2^160 addresses. You might not get a result even in a year.

**Comment by fengshui8** [comment]
How about running 12 instances of the app, each one of said 12 is looking for 1.9 million btc addresses; addresses beginning with a 1.
about ~22.8 million in total.

You think it’s still likely to get no results in 1 year?
