### ISSUE TITLE
how do i edit the code to show the logs ?

### ISSUE THREAD

**Issue by harvs1444** [Michal2SAB/Bitcoin-Stealer#86]
![Screenshot 2023-08-09 024417](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/141793254/1b4809ea-d746-4997-a5df-999c41425061)

**Comment by 3ssenc3** [comment]
help

**Comment by ekkutlu** [comment]
Edit generator.js file
Find this code line
ck.compressed = false;
    //console.log(ck.publicAddress)
    // ^ remove "//" from line above if

Remove //
On which line is "console.log"
