### ISSUE TITLE
can't get this up and running onto ubuntu

### ISSUE THREAD

**Issue by Td-Hill** [Michal2SAB/Bitcoin-Stealer#88]
got to here/
"~/Bitcoin-Stealer/Linux$"
when I try to get the command it does not find it
run.sh or Run.sh : command not found
--
u9@u9-virtual-machine:~/Bitcoin-Stealer/Linux/test$ run.sh
run.sh: command not found
--

**Comment by marssystems** [comment]
Make sure you right click on the .sh file and select Properties -> Permissions and make sure the "allow executing file as program" is checked (enabled). And then to run the run.sh script, you have two options:

(Easiest way) You can double click on the .sh file and select "run in terminal"

Or you can right click on the project folder, select "open in terminal" and then execute the script manually with the following command example: "./run.sh" and hit enter.

**Comment by Td-Hill** [comment]
Still the same as no such file or directory

**Comment by Td-Hill** [comment]
I am on ubuntu 20.4

**Comment by Td-Hill** [comment]
I tried in root and still not allowed to run bash as permission denied
