### ISSUE TITLE
About Wallet Adress

### ISSUE THREAD

**Issue by ekkutlu** [Michal2SAB/Bitcoin-Stealer#89]
Do we need to manually enter the wallet address in the riches txt file?  Or does the program generate addresses itself?  Thanks

**Comment by rg2323** [comment]
i too would like to know

**Comment by marssystems** [comment]
Yes - you have to manually enter the addresses you want to search for into the riches.txt file.

**Comment by GitJhopa** [comment]
> Yes - you have to manually enter the addresses you want to search for into the riches.txt file.

Let's say I entered the necessary addresses, what happens if the program finds them? How will I know about this?

**Comment by marssystems** [comment]
You will see the priv key displayed in the CMD window and a txt file will be produced containing the same info.

Run the test.bat file to see how it works.

**Comment by GitJhopa** [comment]
Thank you. I got it. The question is, can an application generate the same address bitcoin several times?
It’s also interesting, if I receive a SEED phrase, where should I enter it to gain access to the wallet? And an interesting question: what is the chance of finding the right wallet (let’s say I have 30 addresses in the list)?

**Comment by GitJhopa** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/74f18b19-7e6f-4aab-986d-6df2908a76c8)


Please tell me where to upload this Seed phrase? To access your wallet?

**Comment by marssystems** [comment]
You need to enter the seed phrase into your wallet app.

**Comment by GitJhopa** [comment]
> You need to enter the seed phrase into your wallet app.

Trustwallet ? Sorry for asking stupid questions. But I'm looking for wallets from 2009-2013. They were not created in TrustWallet - that's for sure. Where can I open these wallets then? In which applications?

And in general, will your application be able to find these wallets if you are very lucky? I indicated their addresses in riches.txt

**Comment by GitJhopa** [comment]
> You need to enter the seed phrase into your wallet app.

Also, the question is, if I run the application several times, will it speed up the search? Or do you need to run 1 application on one computer?

**Comment by marssystems** [comment]
Yes - you can run more than 1 instance of the program.

**Comment by GitJhopa** [comment]
> Yes - you can run more than 1 instance of the program.

![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/80b5127b-be7e-4595-9587-c7e7f49276bb)
Why is the Seed button not available?

**Comment by marssystems** [comment]
You will have to import the privkey into Bitcoin Core - should you find one.

**Comment by GitJhopa** [comment]
The private key is the Seed that your application finds?

**Comment by GitJhopa** [comment]
I indicated in riches.txt the addresses of Bitcoin wallets that have already been forgotten since 2010-2013. If the wallet finds it, it will give me the Seed of the wallet, but I looked at your example, there was a strange seed, it did not consist of 12 words.

**Comment by marssystems** [comment]
Your seed looks like a WIF file (Wallet Import Format), so you need to import it as text. (!think). I'm not familiar with Electrum.

**Comment by GitJhopa** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/c7a63606-a948-4cb0-a588-3f8d175255cb)

**Comment by marssystems** [comment]
The program will give you the Private Key of the wallet in HEX.

**Comment by GitJhopa** [comment]
Okay, now it’s clearer. What should I do with it next? (help me figure it out, and if I’m lucky, I will definitely thank you very well)

**Comment by GitJhopa** [comment]
Which of these should I take?
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/20aff008-1d7e-4659-9f00-508494fef049)

**Comment by marssystems** [comment]
Try compressed WIF

**Comment by GitJhopa** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/50714da2-1d2c-4d81-ae38-de5f0e477682)

**Comment by GitJhopa** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/f075c8a8-8c0e-42e5-8fc6-c23ee8f0cfc9)

**Comment by GitJhopa** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/750e334b-39d9-4475-a4db-507c7101ce05)

**Comment by GitJhopa** [comment]
no working import key
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/36a2cdfc-14b9-4fd6-bec6-7dbd1bac51be)

**Comment by marssystems** [comment]
Sorry - I don't know.

**Comment by GitJhopa** [comment]
Then what is the point of the application, if even after recognizing the SEED phrase, you cannot use the wallet?

**Comment by GitJhopa** [comment]
I did it.

**Comment by GitJhopa** [comment]
It was necessary not to specify the wallet, but to immediately enter the private key.

**Comment by marssystems** [comment]
It is not a seed phrase - it is a privkey in HEX, which you need to import into your wallet.

**Comment by GitJhopa** [comment]
I just opened this wallet using this key.

**Comment by GitJhopa** [comment]
I simply indicated the key instead of the wallet itself (address) and it opened.

**Comment by marssystems** [comment]
Well there you go - easy !!

**Comment by GitJhopa** [comment]
thank !

**Comment by marssystems** [comment]
Welcome - enjoy !!

**Comment by GitJhopa** [comment]
And the last question. How exactly does your application work, what does it generate? I just see wallet addresses running around in the console and that’s it.

**Comment by GitJhopa** [comment]
It would be cool if you could describe to me the complete logic of the application and how and where it verifies and takes wallet addresses.

**Comment by GitJhopa** [comment]
Such a question, this application can 100% find the key of a Bitcoin wallet that is lost. It just might take 100-1000 years, right? In any case, after going through all the options, he will find all the keys, is that right?

**Comment by GitJhopa** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/98df81e8-cd67-43ce-bb16-fbe3fb5a978f)
Is it possible to make such a checker?

**Comment by marssystems** [comment]
Yes - that's right.

**Comment by GitJhopa** [comment]
> Yes - that's right.

My processor is 9-11% busy with one program running. Can I run 3-4 more copies on one computer? Or is it better not to do this?

**Comment by GitJhopa** [comment]
And if you start it, is it better to create separate folders for each program or can you start it from one folder?

**Comment by GitJhopa** [comment]
Question: In the test folder, I indicated my Bitcoin wallet (address) in test.txt, launched test.bat and nothing happened, but when I indicate your address, which was there, it creates Access.txt, why is that so?
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/a44b1345-72f8-4689-856c-6107c617c41b)

**Comment by GitJhopa** [comment]
Does this app even work and can you find your lost wallet?

**Comment by marssystems** [comment]
If you run the test program, you can see that the program works. It might take a very long time for you to find your lost wallet.

**Comment by MrJorman** [comment]
So why is the address that is specified in test.txt converted to a private key? regular wallet address - not converted

**Comment by MrJorman** [comment]
is it in the database or what? why was I able to get the private key from your address test.txt, but when I specify a different address, nothing happens

**Comment by marssystems** [comment]
The test program is written that way, so you can see what happens when it finds a real privkey. There is no database.

**Comment by GitJhopa** [comment]
Can I run multiple applications? By creating several folders on the computer, since one application eats 8-11% of the CPU

**Comment by marssystems** [comment]
Yes you can - if you have enough RAM to hold the addresses file for each instance of the program.

**Comment by GitJhopa** [comment]
> Yes you can - if you have enough RAM to hold the addresses file for each instance of the program.

![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/86250668/efdeddf4-8792-4fab-8f65-b5179f174b45)

**Comment by GitJhopa** [comment]
64gb RAM

**Comment by marssystems** [comment]
OK - try it.

**Comment by GitJhopa** [comment]
> OK - try it.

Sorry for the questions, but are the addresses generated by the Compressed or Uncompressed program? I have launched about 10 programs so far and I don’t understand, what if it never generates this address that I specified in reaches.txt?

**Comment by marssystems** [comment]
The generator program generates private keys. It then converts the private key into a wallet address and then checks to see it the wallet address is in your riches.txt file. If it is, it prints it out to the CMD window and the success.txt file. If not, it generates another private key and repeats the process.

**Comment by GitJhopa** [comment]
Are there really so many addresses and combinations that people after 5-7 years cannot find private keys or seed phrases?

**Comment by GitJhopa** [comment]
Or are they just hoping for luck? Can someone launch the application and find it right away? And someone may never find it?

**Comment by GitJhopa** [comment]
The private keys generated by the application, do they apply to all Bitcoin addresses? I just heard something about BIP32, BIP44, BIP49 - what does this mean? For example, I’m looking for old addresses from 2009-2014, what BIP do they belong to and will the application generate a private key from them?

**Comment by marssystems** [comment]
No - just the ones beginning with 1......

**Comment by GitJhopa** [comment]
nice.

**Comment by MrJorman** [comment]
What is the chance of finding the right address if there are 100 of them listed? and the program is running on 20 powerful computers?

**Comment by marssystems** [comment]
I  don't know - its random - so it can find an address in the next 10 minutes or maybe never - its like a lottery.

**Comment by GitJhopa** [comment]
> I don't know - its random - so it can find an address in the next 10 minutes or maybe never - its like a lottery.

Can you tell me what line of code I should add so that it saves addresses in log.txt, let’s say those that it checked and sorted through so that addresses are created there.

**Comment by GitJhopa** [comment]
Roughly speaking, the logs should not be in the console, but saved in the file log.txt

**Comment by marssystems** [comment]
Why do you need that? - It doesn't help in any way.

**Comment by GitJhopa** [comment]
I did it already. I want to check duplicates of random addresses and personally see the search for the necessary addresses, in case the application does not search for the necessary addresses or there are many duplicates.

**Comment by marssystems** [comment]
I C - OK.
It will slow down the program BIG TIME ! and fill up your hard disk.

**Comment by GitJhopa** [comment]
> I C - OK. It will slow down the program BIG TIME ! and fill up your hard disk.

Yes, I did it on a separate dedicated machine.

**Comment by GitJhopa** [comment]
https://github.com/albertobsd/keyhunt#testing-puzzle-63-bits this program good ?

**Comment by marssystems** [comment]
I don't know - I have never used it. - Give it a try.

**Comment by GitJhopa** [comment]
Does this application only work with the Internet or will it work the same without the Internet?

**Comment by marssystems** [comment]
What application?

**Comment by marssystems** [comment]
Bitcoin Stealer doesn't need the internet at all.

**Comment by MrJorman** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/55187962/ecdc2169-30cb-4437-b57b-9a1f6b003080)

**Comment by fengshui8** [comment]
@marssystems , I’m currently running 12 instances of the app. Each instance is searching a riches.txt file with approximately 1.9 million different addresses beginning with “1…”.

Overall, the 12 app instances are searching a total ~22.8 million addresses.

Thoughts on this? Been running for many hours now, without hiccup/issue. 
Will the apps each work a lot slower than if they were each searching for maybe 1,000, or 10,000 addresses. 

P.s. 
my rig is fine, RAM wise,
But the cpu is throttling at 100% — likely because I’ve got 12 separate instances running.

**Comment by fengshui8** [comment]
@marssystems theoretically and mathematically—
I feel like the likelihood of a hit has to be way higher— doing it this way.

But maybe I’m wrong?

**Comment by marssystems** [comment]
Sure! - the more instances of the program you run - the higher the chance of finding a wallet.

**Comment by fengshui8** [comment]
@marssystems 

true that. 

But do you have any insight, or any thoughts, regarding the massive “riches.txt” files that I’m searching. 

***Each*** of the 12 instances of the app that I’m running have a **different** 1.9 million addresses (beginning with “1…”).

So the 12 instances of the app are searching roughly 22.8 million different addresses.


Is this too many addresses?
Does this slow each instance of the application down?— like having to cross reference each address output across a riches.txt file with 1.9 million unique addresses?

**Comment by marssystems** [comment]
I don't think the size of the addresses.txt file is a problem. My file contains 24 million addresses. Its all done in memory - so its very fast.

**Comment by fengshui8** [comment]
@Michal2SAB how long have you been running the app for? And have you ever found a wallet?

**Comment by marssystems** [comment]
I don't run this app. I can't get coinkey to work on my computer.

**Comment by kimmelgeek** [comment]
anyone found any wallet with this program
