### ISSUE TITLE
Bug found 

### ISSUE THREAD

**Issue by Zaidi511** [Michal2SAB/Bitcoin-Stealer#91]
![Screenshot_2023-10-01-17-41-02-757_com replit app](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/143783510/d0d8c091-326a-4e6f-9abd-0e2a11de5932)

There are 64 key words in the private key but this shows only 59.

**Comment by fengshui8** [comment]
Was that a genuine hit with this app?

**Comment by Michal2SAB** [comment]
> Was that a genuine hit with this app?

Most likely a troll
