### ISSUE TITLE
Running 12 instances of the app. Is this ok?

### ISSUE THREAD

**Issue by fengshui8** [Michal2SAB/Bitcoin-Stealer#92]
![is this ok](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/150626410/30b56800-4dc4-49a0-93cf-98fd25f5d37e)

is this ok? im running 12 instances of the app for over an hour now, seemingly without issue.

*except for the fact that my CPU is max'd out at 100%...

...No issue with RAM (as i do have 64gb of good ram)... But I'm wondering how efficient this really is-- with the CPU max'd out and all.

Anyone have two cents on the matter?

**Comment by fengshui8** [comment]
Currently running 12 instances of the app, 
each instance is searching for a separate 1.9 million btc addresses (that begin with “1…”).  So actively searching across ~22.8 million btc addresses (that begin with “1…”).


This doesn’t affect my RAM (I’ve got 64GB of good ram,) but my CPU is throttling at 100%. 
Is this okay? 
Do you think the instances of the app are likely underperforming?—If so, how significantly?  

Regardless, do you think it is still worth doing?
Won’t this up the likelihood of a hit significantly in the coming weeks/months? 
& What do you think the likelihood of a hit is?

**Comment by MrJorman** [comment]
0% chance.

**Comment by MrJorman** [comment]
This application is not working correctly. Even if you find the right address, you will not receive a private key, since it is not clear how it works in applications. When you run test.js, it will not give you anything. Just for fun, I used any values from a random address and threw them into test.json and tried to convert them into a private key - nothing worked. So if you find the address, you will not receive the private key.
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/55187962/e5cae756-201e-4c01-bf81-978056f44d96)

**Comment by MrJorman** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/55187962/a829f641-e24e-4af5-a4d4-c7e4bea573ec)

The address that is already in test.txt - it is a template from the coinkey module - thus it is most likely included in the database. You are looking for addresses through this application in vain. You will not be able to obtain the private key. And even if you can, then logically coinkey processes your addresses through its database - that is, another person will receive your found address faster than you. (the one who created coinkey)

**Comment by MrJorman** [comment]
I looked at the code of the application and all the scripts, and still did not understand why it processes this particular address in test.txt, but cannot process others at all. Just for fun, I went to the Bitcoin address generator, where all the data is listed, and just for fun, I took the already known data and substituted it into test.txt and still didn’t get anything.

**Comment by fengshui8** [comment]
@MrJorman bur coinkey doesn’t even require the internet to work …

I don’t think you’re right. I think it might actually work. It’s just about the amount of weeks/months/years that you’re willing to dedicate. 

And still you might not find an address.

**Comment by fengshui8** [comment]
@Michal2SAB , @MrJorman seems to think that it’s impossible for this app to work.  Although it’s statistically improbable, it does work— technically; correct?

**Comment by marssystems** [comment]
Yes - the code is technically correct and works as it should. Whether it will find a privkey for 1 of the addresses in your file is another matter.

**Comment by MrJorman** [comment]
> @Michal2SAB , @MrJorman seems to think that it’s impossible for this app to work. Although it’s statistically improbable, it does work— technically; correct?

It doesn't work well. It also does not know what keys it is looking for, compressed or uncompressed.

**Comment by fengshui8** [comment]
@marssystems 

yeah I hear you.

the odds of it finding one of the 22,900,000 private keys in my .txt files 
 is like 1 in trillions upon trillions, multiplied by billions, 

…right?

**Comment by marssystems** [comment]
Correct !!
