### ISSUE TITLE
Has anyone here actually succeeded with this app?

### ISSUE THREAD

**Issue by fengshui8** [Michal2SAB/Bitcoin-Stealer#93]
Honestly…lol. The odds seem overwhelmingly tiny…

**Comment by marssystems** [comment]
Yes they are.

**Comment by fengshui8** [comment]
@marssystems @Michal2SAB 

wondering how to port all necessary code for generating and checking keys (SHA-256, SHA-512, RIPEMD-160, EC Addition, EC Multiplication, etc.,) to OpenCL C, a programming language to run code on a GPU.

…I feel like utilizing GPU’s and or ASICs to check keys would be exponentially faster/better


@Michal2SAB — have you ever thought about designing this to be more efficient and utilize GPU’s / ASICs?

**Comment by marssystems** [comment]
This will not work on an ASIC - you will need to design a new chip to do this.

**Comment by marssystems** [comment]
Try this for GPU use - https://github.com/Vladimir855/Rotor-Cuda

**Comment by MrJorman** [comment]
> Try this for GPU use - https://github.com/Vladimir855/Rotor-Cuda

hello. --range 1:1fffffffff does this mean that it searches through all possible addresses? or what range should be set to iterate over all ranges of addresses that start with the number 1?

**Comment by marssystems** [comment]
Yes - searches all private keys between 1 and 1fffffffff .

Here are some other ranges you can search -
https://privatekeys.pw/puzzles/bitcoin-puzzle-tx

**Comment by MrJorman** [comment]
> Yes - searches all private keys between 1 and 1fffffffff .
> 
> Here are some other ranges you can search - https://privatekeys.pw/puzzles/bitcoin-puzzle-tx

What range should I specify so that it checks the entire 256 range?

**Comment by marssystems** [comment]
Rotor-Cuda.exe -t 0 --gpu --gpux 256,256,256,256 --gpui 0,1 -n 256 -f base.bin

**Comment by MrJorman** [comment]
> Rotor-Cuda.exe -t 0 --gpu --gpux 256,256,256,256 --gpui 0,1 -n 256 -f base.bin

no working.

**Comment by MrJorman** [comment]
.\Rotor-Cuda.exe -t 0 -g --gpui 0 --gpux 256,256 -m addresses --coin BTC -o Found.txt --range 1:1fffffffff -i hash160_out_sorted.bin -r 5

**Comment by marssystems** [comment]
How many GPU's do you have?

**Comment by MrJorman** [comment]
-n 256 no working args

**Comment by marssystems** [comment]
OK - check the examples on github.

**Comment by marssystems** [comment]
I use this setup -

Rotor-Cuda.exe -d 0 -g --gpui 0 --gpux 256,256 -m ADDRESSES --coin BTC -r 656 -n 1 -z 256 -i 1FullAddSorted.bin

Are you running this on Windows with Nvidia GPU's ?

**Comment by marssystems** [comment]
Here is a different version -

https://github.com/Mehdi256/Rotor-Cuda/tree/main
