### ISSUE TITLE
Help me to run this

### ISSUE THREAD

**Issue by harshana69812** [Michal2SAB/Bitcoin-Stealer#94]
I don't understand run this program,youtube video also deleted,help me

**Comment by marssystems** [comment]
What problem do you have?

**Comment by harshana69812** [comment]
can you please give small video about run this program

**Comment by marssystems** [comment]
No - I don't have a video.

**Comment by harshana69812** [comment]
can you explain step by step after extract

**Comment by marssystems** [comment]
After extract go to the Windows folder and click on the run.bat file - that's it.

**Comment by harshana69812** [comment]
![Screenshot (302)](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/131577574/3403eaef-486e-47b2-89a2-2ebaaee1f7a8)

**Comment by marssystems** [comment]
Open cmd window and type this command: npm i coinkey -g

**Comment by MrJorman** [comment]
> Open cmd window and type this command: npm i coinkey -g

hello bro. https://privatekeyfinder.io/private-keys/bitcoin/ Do you think it’s possible to find all the private keys on this site? Will I be able to find all forgotten wallets with balances? Just for fun, I looked at my private keys of 3 Bitcoin wallets and found them with a balance. But I think maybe this is a ready-made wallet base without balances? What do you think?

**Comment by marssystems** [comment]
Sure! - its possible. Given enough time, you can find any/all private keys.

**Comment by MrJorman** [comment]
> Sure! - its possible. Given enough time, you can find any/all private keys.

thank you! I hope that your answer was not banter or a joke ))

**Comment by marssystems** [comment]
There are 115792089237316195423570985008687907853269984665640564039457584007913129639936 private keys - so it will take you quite some time to check them all - no joke!

**Comment by MrJorman** [comment]
> There are 115792089237316195423570985008687907853269984665640564039457584007913129639936 private keys - so it will take you quite some time to check them all - no joke!

https://keysfinder.net/ Actually, I'm looking here. But I also use a random page search and have 60 open windows for checking. And I’m thinking, this isn’t a scam? Is this really a working site where you can easily find private keys all wallets with balances?

**Comment by marssystems** [comment]
just as easy to find a private key for a wallet with a balance using this website as using any other method. The number of privaate keys to search through is the same.

**Comment by MrJorman** [comment]
Easily? Ahah, this is the 10th day I’ve been sitting at the monitor for 14 hours and updating 60 pages every 20 seconds, until everything is 0.

**Comment by MrJorman** [comment]
I would like a script for the browser that would refresh the page and check the balance, if it is greater than 0, then the script stops, if 0 = then it refreshes the page again. Maybe you know how to do something like this? I would pay you or share bitcoins after the find.

**Comment by MrJorman** [comment]
![image](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/55187962/6959b0e1-9b61-428d-83d2-4621f109f833)
I have a lot of computers and huge monitors, but I would really like a script to automatically update the page on this site and check the balance.

**Comment by marssystems** [comment]
Just run the Bitcoin Stealer program it does the same thing 10000 times faster than any website all by itself.

**Comment by MrJorman** [comment]
> Just run the Bitcoin Stealer program it does the same thing 10000 times faster than any website all by itself.

It's clear. But I also want to do this through the site with my own hands.

**Comment by MrJorman** [comment]
More options = more chances.

**Comment by marssystems** [comment]
Sure! - no worries!

**Comment by MrJorman** [comment]
https://github.com/Pymmdrza/Pyromid Is this app worse than Bitcoin Stealer?

**Comment by marssystems** [comment]
I don't know - you can try it and see.

**Comment by harshana69812** [comment]
![Screenshot (303)](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/131577574/f3529e1b-55c4-4adc-8d24-05b19e927a94)
can't type anything close window at once

**Comment by MrJorman** [comment]
you don't install module CoinKey

**Comment by MrJorman** [comment]
write in powershell console (SHIFT+Right Click Mouse) = start powershell console and write command - npm i

**Comment by harshana69812** [comment]
then?

**Comment by Zecxy** [comment]
> Open cmd window and type this command: npm i coinkey -g

tried your command, got 'packs need funding' not sure if it matters. however when trying to run the code again vai run.bat, code still gives the same response, cannot find module coinkey

**Comment by rayu79** [comment]
Doesn't work for me either

**Comment by Haxes0** [comment]
> g
Are the program working like this?
![IMG_5717](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/162243723/a0eb9db1-43f9-4f80-9df9-467dc9763500)

**Comment by Haxes0** [comment]
> After extract go to the Windows folder and click on the run.bat file - that's it.

what is extract you mean?

**Comment by swindle0907** [comment]
> ![Screenshot (303)](https://github.com/Michal2SAB/Bitcoin-Stealer/assets/131577574/f3529e1b-55c4-4adc-8d24-05b19e927a94)
> 
> can't type anything close window at once 

run, "npm i coinkey -g", then just run "npm fund" then "run.bat" (for windows)

**Comment by neverm8** [comment]
Clear all your settings and just go and do a complete new download - update any proxies that you need and then email me the link
