### ISSUE TITLE
Hacking/Recovery

### ISSUE THREAD

**Issue by mercycole** [Michal2SAB/Bitcoin-Stealer#96]
SCAMS COME IN MANY FORMS, BUT ALL ARE DESIGNED TO GET A HOLD OF YOUR HARD-EARNED MONEY. The first mistake I made was thinking I could multiply my income by investing in cryptocurrency, I fell for a popular investment scam and was swindled of $60,000 in bitcoins. After a few weeks, I came across a pop-up while browsing the internet about a recovery team called James that could help me recover my bitcoins in a matter of hours, I was doubtful about it at first but I finally contacted them and in a space of 48 hours, Mr. James Mckay Wizard was able to recover all of my money lost in bitcoins. They are the best bitcoins recovery team out there and if you face similar issues, you should contact them immediately. Contact information: jamesmckaywizard@gmail.com /What's App:+44 7826 613094

**Comment by marssystems** [comment]
This is rubbish. It's another scam !!  Once bitcoins are transferred from your wallet they are NOT recoverable - unless the person who has your coins sends them back to you voluntarily. So don't contact this Mr. James (fake name) person or you will be scammed for sure!
